# Generated by Django 3.2 on 2021-08-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='product_imag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='titlle',
            new_name='title',
        ),
    ]
