# Generated by Django 3.2 on 2021-08-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_product_imag_product_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='product_imag',
        ),
    ]
